{{ if .Values.runtime.aktoApiSecurityRuntime.env.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "akto.fullname" . }}-runtime
  labels:
  {{- include "akto.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.runtime.replicas }}
  selector:
    matchLabels:
      app: {{ include "akto.fullname" . }}-runtime
    {{- include "akto.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "akto.fullname" . }}-runtime
      {{- include "akto.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: kafka-secrets-vol
          secret:
            secretName: "kafka-secrets"
            items:
              - key: kafka-keystore.jks
                path: kafka-keystore.jks
              - key: kafka-truststore.jks
                path: kafka-truststore.jks
              - key: kafka-client-truststore
                path: kafka-client-truststore.jks
              - key: kafka-client-jaas
                path: kafka_client_jaas.conf
              - key: kafka-server-jaas
                path: kafka_server_jaas.conf
              - key: zookeeper-jaas
                path: zookeeper_jaas.conf
              - key: store-credentials
                path: store-credentials    
      containers:
      - env:
        - name: AKTO_ACCOUNT_NAME
          value: {{ quote .Values.runtime.aktoApiSecurityRuntime.env.aktoAccountName }}
        - name: IS_KUBERNETES
          value: "true"
        - name: AKTO_CONFIG_NAME
          value: {{ quote .Values.runtime.aktoApiSecurityRuntime.env.aktoConfigName }}
        - name: AKTO_INSTANCE_TYPE
          value: {{ quote .Values.runtime.aktoApiSecurityRuntime.env.aktoInstanceType }}
        - name: AKTO_KAFKA_BROKER_MAL
          value: {{ quote .Values.runtime.aktoApiSecurityRuntime.env.aktoKafkaBrokerMal
            }}
        - name: AKTO_KAFKA_BROKER_URL
          value: {{ quote .Values.runtime.aktoApiSecurityRuntime.env.aktoKafkaBrokerUrl
            }}
        - name: AKTO_KAFKA_GROUP_ID_CONFIG
          value: {{ quote .Values.runtime.aktoApiSecurityRuntime.env.aktoKafkaGroupIdConfig
            }}
        - name: AKTO_KAFKA_MAX_POLL_RECORDS_CONFIG
          value: {{ quote .Values.runtime.aktoApiSecurityRuntime.env.aktoKafkaMaxPollRecordsConfig
            }}
        - name: AKTO_KAFKA_TOPIC_NAME
          value: {{ quote .Values.runtime.aktoApiSecurityRuntime.env.aktoKafkaTopicName
            }}
        - name: AKTO_TRAFFIC_BATCH_SIZE
          value: {{ quote .Values.runtime.aktoApiSecurityRuntime.env.aktoTrafficBatchSize
            }}
        - name: AKTO_TRAFFIC_BATCH_TIME_SECS
          value: {{ quote .Values.runtime.aktoApiSecurityRuntime.env.aktoTrafficBatchTimeSecs
            }}
        - name: PUPPETEER_REPLAY_SERVICE_URL
          value: {{ quote .Values.runtime.aktoApiSecurityRuntime.env.puppeteerReplayServiceUrl
            }}
        - name: AKTO_MONGO_CONN
          value: {{ quote .Values.mongo.aktoMongoConn }}
        - name: USE_HOSTNAME
          value: {{ quote .Values.runtime.aktoApiSecurityRuntime.env.useHostName}}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: "{{ .Values.runtime.aktoApiSecurityRuntime.image.repository }}:{{ .Values.runtime.aktoApiSecurityRuntime.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.runtime.aktoApiSecurityRuntime.imagePullPolicy }}
        name: akto-api-security-runtime
        resources: {{- toYaml .Values.runtime.aktoApiSecurityRuntime.resources |  nindent 10 }}
      - env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: {{ quote .Values.runtime.zoo1.env.zookeeperClientPort }}
        - name: ZOOKEEPER_SERVERS
          value: {{ quote .Values.runtime.zoo1.env.zookeeperServers }}
        - name: ZOOKEEPER_SERVER_ID
          value: {{ quote .Values.runtime.zoo1.env.zookeeperServerId }}
        - name: KAFKA_OPTS
          value: {{ quote .Values.runtime.zoo1.env.kafkaOpts }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: "{{ .Values.runtime.zoo1.image.repository }}:{{ .Values.runtime.zoo1.image.tag | default .Chart.AppVersion }}"
        name: zoo1
        ports:
        - containerPort: 2181
        resources: {{- toYaml .Values.runtime.zoo1.resources | nindent 10 }}
      - env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "LISTENER_DOCKER_EXTERNAL_LOCALHOST://localhost:29092, LISTENER_DOCKER_EXTERNAL_DIFFHOST://{{.Release.Name}}-{{.Chart.Name}}-runtime.{{.Release.Namespace}}.svc.cluster.local:9092"
        - name: KAFKA_BROKER_ID
          value: {{ quote .Values.runtime.kafka1.env.kafkaBrokerId }}
        - name: KAFKA_CLEANUP_POLICY
          value: {{ quote .Values.runtime.kafka1.env.kafkaCleanupPolicy }}
        - name: KAFKA_CREATE_TOPICS
          value: {{ quote .Values.runtime.kafka1.env.kafkaCreateTopics }}
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: {{ quote .Values.runtime.kafka1.env.kafkaInterBrokerListenerName }}
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: {{ quote .Values.runtime.kafka1.env.kafkaListenerSecurityProtocolMap }}
        - name: KAFKA_LOG_CLEANER_ENABLE
          value: {{ quote .Values.runtime.kafka1.env.kafkaLogCleanerEnable }}
#        - name: KAFKA_LOG_RETENTION_BYTES
#          value: {{ quote .Values.runtime.kafka1.env.kafkaLogRetentionBytes }}
#        - name: KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS
#          value: {{ quote .Values.runtime.kafka1.env.kafkaLogRetentionCheckIntervalMs }}
#        - name: KAFKA_LOG_RETENTION_HOURS
#          value: {{ quote .Values.runtime.kafka1.env.kafkaLogRetentionHours }}
#        - name: KAFKA_LOG_SEGMENT_BYTES
#          value: {{ quote .Values.runtime.kafka1.env.kafkaLogSegmentBytes }}
        - name: KAFKA_SASL_ENABLED_MECHANISMS
          value: {{ quote .Values.runtime.kafka1.env.kafkaSaslEnabledMachine }}
        - name: KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL
          value: {{ quote .Values.runtime.kafka1.env.kafkaSaslEnabledInterBrokerProtocal }}
        - name: KAFKA_SOCKET_REQUEST_MAX_BYTES
          value: {{ quote .Values.runtime.kafka1.env.kafkaMaxRequestSize }}
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: {{ quote .Values.runtime.kafka1.env.kafkaOffsetsTopicReplicationFactor
            }}
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: {{ quote .Values.runtime.kafka1.env.kafkaTransactionStateLogMinIsr }}
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: {{ quote .Values.runtime.kafka1.env.kafkaTransactionStateLogReplicationFactor
            }}
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: {{ quote .Values.runtime.kafka1.env.kafkaZookeeperConnect }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: "{{ .Values.runtime.kafka1.image.repository }}:{{ .Values.runtime.kafka1.image.tag | default .Chart.AppVersion }}"
        name: kafka1
        ports:
        - containerPort: 9092
        - containerPort: 19092
        - containerPort: 29092
        - containerPort: 9999
        resources: {{- toYaml .Values.runtime.kafka1.resources | nindent 10 }}
      restartPolicy: Always
{{ end }}