{{ if .Values.dashboard.aktoApiSecurityDashboard.env.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "akto.fullname" . }}-dashboard
  labels:
  {{- include "akto.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.dashboard.replicas }}
  selector:
    matchLabels:
      app: {{ include "akto.fullname" . }}-dashboard
    {{- include "akto.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "akto.fullname" . }}-dashboard
      {{- include "akto.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: AKTO_ACCOUNT_NAME
          value: {{ quote .Values.dashboard.aktoApiSecurityDashboard.env.aktoAccountName
            }}
        - name: IS_KUBERNETES
          value: "true"
        - name: AKTO_CONFIG_NAME
          value: {{ quote .Values.dashboard.aktoApiSecurityDashboard.env.aktoConfigName
            }}
        - name: AKTO_INSTANCE_TYPE
          value: {{ quote .Values.dashboard.aktoApiSecurityDashboard.env.aktoInstanceType
            }}
        - name: AKTO_KAFKA_BROKER_MAL
          value: {{ quote .Values.dashboard.aktoApiSecurityDashboard.env.aktoKafkaBrokerMal
            }}
        - name: AKTO_KAFKA_BROKER_URL
          value: {{ quote .Values.dashboard.aktoApiSecurityDashboard.env.aktoKafkaBrokerUrl
            }}
        - name: AKTO_KAFKA_GROUP_ID_CONFIG
          value: {{ quote .Values.dashboard.aktoApiSecurityDashboard.env.aktoKafkaGroupIdConfig
            }}
        - name: AKTO_KAFKA_MAX_POLL_RECORDS_CONFIG
          value: {{ quote .Values.dashboard.aktoApiSecurityDashboard.env.aktoKafkaMaxPollRecordsConfig
            }}
        - name: AKTO_KAFKA_TOPIC_NAME
          value: {{ quote .Values.dashboard.aktoApiSecurityDashboard.env.aktoKafkaTopicName
            }}
        - name: AKTO_TRAFFIC_BATCH_SIZE
          value: {{ quote .Values.dashboard.aktoApiSecurityDashboard.env.aktoTrafficBatchSize
            }}
        - name: AKTO_TRAFFIC_BATCH_TIME_SECS
          value: {{ quote .Values.dashboard.aktoApiSecurityDashboard.env.aktoTrafficBatchTimeSecs
            }}
        - name: PUPPETEER_REPLAY_SERVICE_URL
          value: {{ quote .Values.dashboard.aktoApiSecurityDashboard.env.puppeteerReplayServiceUrl
            }}
        - name: AKTO_MONGO_CONN
          value: {{ quote .Values.mongo.aktoMongoConn
            }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: "{{ .Values.dashboard.aktoApiSecurityDashboard.image.repository }}:{{ .Values.dashboard.aktoApiSecurityDashboard.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.dashboard.aktoApiSecurityDashboard.imagePullPolicy
          }}
        name: akto-api-security-dashboard
        ports:
        - containerPort: 8080
        resources: {{- toYaml .Values.dashboard.aktoApiSecurityDashboard.resources |  nindent 10 }}
      - name: akto-api-security-puppeteer-replay
        image: "{{ .Values.dashboard.aktoApiSecurityPuppeteerReplay.image.repository }}:{{ .Values.dashboard.aktoApiSecurityPuppeteerReplay.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.dashboard.aktoApiSecurityPuppeteerReplay.imagePullPolicy }}
        ports:
          - containerPort: 3000
        resources: {{- toYaml .Values.dashboard.aktoApiSecurityPuppeteerReplay.resources |  nindent 10 }}
{{ end }}
---
{{ if .Values.testing.aktoApiSecurityTesting.env.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "akto.fullname" . }}-testing
  labels:
  {{- include "akto.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.testing.replicas }}
  selector:
    matchLabels:
      app: {{ include "akto.fullname" . }}-testing
    {{- include "akto.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "akto.fullname" . }}-testing
      {{- include "akto.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: AKTO_ACCOUNT_NAME
          value: {{ quote .Values.testing.aktoApiSecurityTesting.env.aktoAccountName }}
        - name: IS_KUBERNETES
          value: "true"
        - name: AKTO_CONFIG_NAME
          value: {{ quote .Values.testing.aktoApiSecurityTesting.env.aktoConfigName }}
        - name: AKTO_INSTANCE_TYPE
          value: {{ quote .Values.testing.aktoApiSecurityTesting.env.aktoInstanceType }}
        - name: AKTO_KAFKA_BROKER_MAL
          value: {{ quote .Values.testing.aktoApiSecurityTesting.env.aktoKafkaBrokerMal
            }}
        - name: AKTO_KAFKA_BROKER_URL
          value: {{ quote .Values.testing.aktoApiSecurityTesting.env.aktoKafkaBrokerUrl
            }}
        - name: AKTO_KAFKA_GROUP_ID_CONFIG
          value: {{ quote .Values.testing.aktoApiSecurityTesting.env.aktoKafkaGroupIdConfig
            }}
        - name: AKTO_KAFKA_MAX_POLL_RECORDS_CONFIG
          value: {{ quote .Values.testing.aktoApiSecurityTesting.env.aktoKafkaMaxPollRecordsConfig
            }}
        - name: AKTO_KAFKA_TOPIC_NAME
          value: {{ quote .Values.testing.aktoApiSecurityTesting.env.aktoKafkaTopicName
            }}
        - name: AKTO_TRAFFIC_BATCH_SIZE
          value: {{ quote .Values.testing.aktoApiSecurityTesting.env.aktoTrafficBatchSize
            }}
        - name: AKTO_TRAFFIC_BATCH_TIME_SECS
          value: {{ quote .Values.testing.aktoApiSecurityTesting.env.aktoTrafficBatchTimeSecs
            }}
        - name: PUPPETEER_REPLAY_SERVICE_URL
          value: {{ quote .Values.testing.aktoApiSecurityTesting.env.puppeteerReplayServiceUrl
            }}
        - name: AKTO_MONGO_CONN
          value: {{ quote .Values.mongo.aktoMongoConn }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: "{{ .Values.testing.aktoApiSecurityTesting.image.repository }}:{{ .Values.testing.aktoApiSecurityTesting.image.tag | default .Chart.AppVersion }}"
        name: akto-api-security-testing
        resources: {{- toYaml .Values.testing.aktoApiSecurityTesting.resources |  nindent 10 }}
      - name: akto-api-security-puppeteer-replay
        image: "{{ .Values.testing.aktoApiSecurityPuppeteerReplay.image.repository }}:{{ .Values.testing.aktoApiSecurityPuppeteerReplay.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.testing.aktoApiSecurityPuppeteerReplay.imagePullPolicy }}
        ports:
          - containerPort: 3000
        resources: {{- toYaml .Values.testing.aktoApiSecurityPuppeteerReplay.resources |  nindent 10 }}
      restartPolicy: Always
{{ end }}